export const TESTING_BOOKS = [
  {
    ID: 1,
    title: "harry potter",
    description: "harry potter description",
    price: 200,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["JK Rowling"],
    categories: ["Magic"],
    publisher: "Salamandra Infantil Y Juvenil",
    publishedDate: "2021-08-24",
    pageCount: 608,
    rating: 4,
    language: "es",
  },
  {
    ID: 2,
    title: "sherlock holmes",
    description: "sherlock holmes description",
    price: 20000,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["Arthur Conan Doyle"],
    categories: ["Detective"],
    publisher: "any publiser",
    publishedDate: "1930-05-22",
    pageCount: 400,
    rating: 3,
    language: "es",
  },
  {
    ID: 3,
    title: "some book",
    description: "some book description",
    price: 100,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["new author"],
    categories: ["SomeCategory"],
    publisher: "any publisher",
    publishedDate: "1999-02-23",
    pageCount: 62,
    rating: 5,
    language: "es",
  },
  {
    ID: 4,
    title: "another book",
    description: "another book description",
    price: 700,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["Another author"],
    categories: ["AnotherCategory"],
    publisher: "any publisher",
    publishedDate: "2003-01-02",
    pageCount: 608,
    rating: 1,
    language: "es",
  },
  {
    ID: 5,
    title: "special book",
    description: "special description",
    price: 100,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["SpecialAuthor"],
    categories: ["SpecialCategory"],
    publisher: "any publisher",
    publishedDate: "1990-01-01",
    pageCount: 608,
    rating: 3,
    language: "es",
  },
  {
    ID: 6,
    title: "lonely book",
    description: "lonely book description",
    price: 2500,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["lonely author"],
    categories: ["Lonely"],
    publisher: "any publisher",
    publishedDate: "2020-07-11",
    pageCount: 608,
    rating: 4,
    language: "es",
  },
  {
    ID: 7,
    title: "Wow book",
    description: "wow description",
    price: 2100,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["Wow author"],
    categories: ["Wow magic"],
    publisher: "any publisher",
    publishedDate: "2010-12-02",
    pageCount: 608,
    rating: 4,
    language: "es",
  },
  {
    ID: 8,
    title: "Stranger Book",
    description: "OMG Stranger Book description",
    price: 3300,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["Best Author"],
    categories: ["Paranormal"],
    publisher: "any publisher",
    publishedDate: "2015-04-04",
    pageCount: 608,
    rating: 1,
    language: "es",
  },
  {
    ID: 9,
    title: "come read my book",
    description: "weird book description",
    price: 2200,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["Weird"],
    categories: ["Crazy"],
    publisher: "any publisher",
    publishedDate: "2001-01-21",
    pageCount: 608,
    rating: 2,
    language: "es",
  },
  {
    ID: 10,
    title: "crime book",
    description: "crime book description",
    price: 5000,
    image: "https://images-na.ssl-images-amazon.com/images/I/91R1AixEiLL.jpg",
    authors: ["Killer Jackson"],
    categories: ["Crime"],
    publisher: "any publisher",
    publishedDate: "1995-11-15",
    pageCount: 608,
    rating: 5,
    language: "es",
  },
];
export const TESTING_USERS = [
  {
    ID: 1,
    name: "Some",
    surname: "One",
    username: "someOne",
    mail: "someOne@gmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
  {
    ID: 2,
    name: "Clara",
    surname: "Arguello",
    username: "clari.arguello",
    mail: "claraArguello11@gmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
  {
    ID: 3,
    name: "Nacho",
    surname: "Losa",
    username: "nacho.losa",
    mail: "nacholosa22@hotmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
  {
    ID: 4,
    name: "Esteban",
    surname: "Manrupe",
    username: "peurman",
    mail: "peurman33@gmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
  {
    ID: 5,
    name: "Tomas",
    surname: "Borquez",
    username: "tomi.bor",
    mail: "tomasbor44@gmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
  {
    ID: 6,
    name: "Bruno",
    surname: "Pizarro",
    username: "bruno.p",
    mail: "brunop55@gmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
  {
    ID: 7,
    name: "Mariano",
    surname: "Ceballos",
    username: "marianC",
    mail: "ceballos65@gmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
  {
    ID: 8,
    name: "Aldo",
    surname: "Moro",
    username: "moro.aldo",
    mail: "aldomoro77@gmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
  {
    ID: 9,
    name: "Enrique",
    surname: "Garay",
    username: "quique",
    mail: "quiquegaray81@gmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
  {
    ID: 10,
    name: "Franco",
    surname: "Etcheverri",
    username: "fran.etcheverri",
    mail: "etcheverri123@gmail.com",
    image:
      "https://i.pinimg.com/474x/8f/1b/09/8f1b09269d8df868039a5f9db169a772.jpg",
  },
];
